---
- hosts: _kafka_cluster
  become: yes
  vars:
    kafka_version: 3.4.0 
    scala_version: 2.13
    kafka_user: kafka
    kafka_group: kafka
    kafka_home: /opt/kafka
    kafka_download_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka-{{ kafka_version }}-src.tgz"
    kafka_download_dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    kafka_config_file: "{{ kafka_home }}/config/server.properties" 
  tasks:
  - name: Install necessary packages
    apt:
      name: 
        - curl
      state: present

  - name: Add kafka user
    user:
      name: "{{ kafka_user }}"
      system: yes
      state: present
      shell: /bin/false
      home: "{{ kafka_home }}"
      create_home: yes

  
  - name: Download Kafka
    get_url:
      url: "{{ kafka_download_url }}"
      dest: "{{ kafka_download_dest }}"
      mode: '0755'
    
  - name: Extract Kafka to the defined destination directory
    unarchive:
      src: "{{ kafka_download_dest }}"
      dest: /opt
      remote_src: yes
      owner: "{{ kafka_user }}"
      group: "{{ kafka_group }}"
      creates: "{{ kafka_home }}"

  - name: Create Kafka config directory
    file:
      path: /opt/kafka/config
      state: directory
      mode: '0755'
  
  - name: Configure server.properties
    template:
      src: server.properties.j2
      dest: "{{ kafka_config_file }}"
      owner: "{{ kafka_user }}"
      group: "{{ kafka_group }}"
      mode: u=rwX,g=rX,o=rX
  
  - name: Setup Kafka service
    template:
      src: kafka.service.j2
      dest: /etc/systemd/system/kafka.service
      mode: '0644'
    notify: restart kafka

  handlers:
  - name: restart kafka
    systemd:
      name: kafka
      state: restarted
      enabled: yes
...
