apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:tejpratap545/ecom.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.prod.yaml
      parameters:
      - name: image.tag
        value: vlatest
    path: my-chart
    chart: my-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true